# Generated by Django 5.0.4 on 2024-05-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_companies_subcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='companies',
            new_name='Company',
        ),
    ]
