# Generated by Django 5.0.4 on 2024-06-06 17:20

import companies.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_options'),
        ('products', '0003_product_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('website', models.TextField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=14)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('company_logo', models.ImageField(upload_to=companies.models.Company.get_img_upload_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('products', models.ManyToManyField(to='products.product')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
