# Generated by Django 5.0.4 on 2024-06-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_logo',
            new_name='image',
        ),
    ]
