# Generated by Django 5.0.4 on 2024-06-06 17:09

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company_logo',
            field=models.ImageField(default=True, upload_to=products.models.Product.get_img_upload_path),
            preserve_default=False,
        ),
    ]
